### ISSUE TITLE
Recently released version is breaking nuxt 2 build - v7.21.0-placeholder-for-preset-env.2

### ISSUE THREAD

**Issue by hs-tunji-oyeniran** [babel/babel-plugin-proposal-private-property-in-object#1]
**Screenshot**

<img width="1443" alt="image" src="https://github.com/babel/babel-plugin-proposal-private-property-in-object/assets/95655956/f0173758-9637-4dda-a270-0b86ef2445a9">

<img width="754" alt="image" src="https://github.com/babel/babel-plugin-proposal-private-property-in-object/assets/95655956/e76b15bb-3bd5-4e80-acd0-d84299909520">

I have added the package `@babel/plugin-proposal-private-property-in-object without` to `devDependencies` and the issue is still the same. Noticed the issue is with the latest version `v7.21.0-placeholder-for-preset-env.2` released about 20 hours ago.

**Comment by hs-tunji-oyeniran** [comment]
**Same Issue on StackOverflow**
https://stackoverflow.com/questions/76435306/babel-preset-react-app-is-importing-the-babel-plugin-proposal-private-propert

**Comment by nicolo-ribaudo** [comment]
It looks like `@nuxt/babel-preset-app` is importing `@babel/plugin-proposal-private-property-in-object` without specifying which version of the package it wants. `@babel/plugin-proposal-private-property-in-object@v7.21.0-placeholder-for-preset-env.2` is a pre-release with a breaking change (and it's ok to have breaking change in pre-releases, since ^7.21.0 wouldn't match it), but since `@nuxt/babel-preset-app` is not specifying which version of the dependency it wants it's receiving the one wrong one.

@danielroe Any chances that this could be fixed in `@nuxt/babel-preset-app` itself? It is importing the package at https://github.com/nuxt/nuxt/blob/27e450119cbc30a4b1d94acef21c905df93160a3/packages/babel-preset-app/src/index.js#L161 but it's not defined in `package.json`.

We added a workaround for a similar bug with create-react-app because CRA is not maintained anymore, but I'd rather avoid doing it for packages that can release a fix.

**Comment by danielroe** [comment]
Yes, we can fix that 👍

**Comment by daniluk4000** [comment]
I've created separate issue for this: https://github.com/babel/babel/issues/15694

@nicolo-ribaudo why did it have to break anything at all?

**Comment by leongaban** [comment]
Hi I just ran a brand new create-react-app command, in Mar 2024 and still got this error?

https://stackoverflow.com/questions/76435306/babel-preset-react-app-is-importing-the-babel-plugin-proposal-private-propert

Had to run this command to fix the error:

`npm install --save-dev @babel/plugin-proposal-private-property-in-object`

**Comment by nicolo-ribaudo** [comment]
> in Mar 2024 and still got this error?

Yes, create-react-app is not maintained anymore so they'll never fix it.
