### ISSUE TITLE
Package version does not comply with semver rules

### ISSUE THREAD

**Issue by CrazyWood007** [babel/babel-plugin-proposal-private-property-in-object#2]
For example :`7.21.0-placeholder-for-preset-env.2` .
This version mismatch with semver rules and its too long.
I wonder if you'll republish it.

**Comment by nicolo-ribaudo** [comment]
Which semver rule are we breaking?

1. It's a pre-release, so it can contain any change because if your `package.json` specifies something like `^7.0.0` or `^7.21.0` it will not download this version
2. Semver does not specify any limit on the version length

This version follows the same pattern as, for example, `7.21.0-alpha.1`.

Semver spec: https://semver.org/

**Comment by nicolo-ribaudo** [comment]
You can verify it on https://semver.npmjs.com/:

<img width="1157" alt="image" src="https://github.com/babel/babel-plugin-proposal-private-property-in-object/assets/7000710/2e6db983-5cb5-4854-9cb4-5dd938ea2f0c">

**Comment by CrazyWood007** [comment]
I'm sorry, I use `latest` in my package.json. : (

**Comment by nicolo-ribaudo** [comment]
I just (~15) minutes ago fixed `latest` to point to 7.22.21 again, so if you re-install the dependency it should work again.

However, I suggest _never_ using `latest` since it's basically saying "I do not care about semver, just give me the latest published version of the package even if it has breaking changes".
